//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTI.Modules.Shared.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GTI.Modules.Shared.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AboutBack {
            get {
                object obj = ResourceManager.GetObject("AboutBack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {0}.
        /// </summary>
        internal static string AboutBoxAbout {
            get {
                return ResourceManager.GetString("AboutBoxAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account #:.
        /// </summary>
        internal static string AccountNumberString {
            get {
                return ResourceManager.GetString("AccountNumberString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auth Code:.
        /// </summary>
        internal static string AuthCode {
            get {
                return ResourceManager.GetString("AuthCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B3 Jackpot Receipt.
        /// </summary>
        internal static string B3JackpotReceiptTitle {
            get {
                return ResourceManager.GetString("B3JackpotReceiptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of session redemption voucher.
        /// </summary>
        internal static string B3OutOfSessioNRedeemReceiptTitle {
            get {
                return ResourceManager.GetString("B3OutOfSessioNRedeemReceiptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B3 Redeem Receipt.
        /// </summary>
        internal static string B3RedeemReceiptTitle {
            get {
                return ResourceManager.GetString("B3RedeemReceiptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B3 Sales Receipt.
        /// </summary>
        internal static string B3SaleReceiptTitle {
            get {
                return ResourceManager.GetString("B3SaleReceiptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B3 Unlock Receipt.
        /// </summary>
        internal static string B3UnlockReceiptTitle {
            get {
                return ResourceManager.GetString("B3UnlockReceiptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:.
        /// </summary>
        internal static string BankAdjustReceiptCurrency {
            get {
                return ResourceManager.GetString("BankAdjustReceiptCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Close Receipt.
        /// </summary>
        internal static string BankAdjustReceiptTitleClose {
            get {
                return ResourceManager.GetString("BankAdjustReceiptTitleClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Drop Receipt.
        /// </summary>
        internal static string BankAdjustReceiptTitleDrop {
            get {
                return ResourceManager.GetString("BankAdjustReceiptTitleDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Issue Receipt.
        /// </summary>
        internal static string BankAdjustReceiptTitleIssue {
            get {
                return ResourceManager.GetString("BankAdjustReceiptTitleIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BigBlueButtonDown {
            get {
                object obj = ResourceManager.GetObject("BigBlueButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BigBlueButtonUp {
            get {
                object obj = ResourceManager.GetObject("BigBlueButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BingoCard75 {
            get {
                object obj = ResourceManager.GetObject("BingoCard75", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BingoCard80 {
            get {
                object obj = ResourceManager.GetObject("BingoCard80", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BingoCard90 {
            get {
                object obj = ResourceManager.GetObject("BingoCard90", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BONUS {0:D2} {1:D2} {2:D2}.
        /// </summary>
        internal static string BingoCardBonus {
            get {
                return ResourceManager.GetString("BingoCardBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BingoCardCBB {
            get {
                object obj = ResourceManager.GetObject("BingoCardCBB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   B     I     N     G     O  .
        /// </summary>
        internal static string BingoCardDAHeader {
            get {
                return ResourceManager.GetString("BingoCardDAHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   L     O     T     T     O  .
        /// </summary>
        internal static string BingoCardDAHeaderLotto {
            get {
                return ResourceManager.GetString("BingoCardDAHeaderLotto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BingoCardQuickDraw {
            get {
                object obj = ResourceManager.GetObject("BingoCardQuickDraw", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuickDraw.
        /// </summary>
        internal static string BingoCardQuickDrawHeader {
            get {
                return ResourceManager.GetString("BingoCardQuickDrawHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B  I  N  G  O .
        /// </summary>
        internal static string BingoCardStandardHeader {
            get {
                return ResourceManager.GetString("BingoCardStandardHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L  O  T  T  O .
        /// </summary>
        internal static string BingoCardStandardHeaderLotto {
            get {
                return ResourceManager.GetString("BingoCardStandardHeaderLotto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STAR {0:D2}.
        /// </summary>
        internal static string BingoCardStar {
            get {
                return ResourceManager.GetString("BingoCardStar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bingo card face is too long!.
        /// </summary>
        internal static string BingoCardTooLong {
            get {
                return ResourceManager.GetString("BingoCardTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BlueButtonDown {
            get {
                object obj = ResourceManager.GetObject("BlueButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BlueButtonUp {
            get {
                object obj = ResourceManager.GetObject("BlueButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number is required!.
        /// </summary>
        internal static string CardSearchError {
            get {
                return ResourceManager.GetString("CardSearchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  E:.
        /// </summary>
        internal static string CBBElecCard {
            get {
                return ResourceManager.GetString("CBBElecCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  P:.
        /// </summary>
        internal static string CBBPaperCard {
            get {
                return ResourceManager.GetString("CBBPaperCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Cash Out Receipt.
        /// </summary>
        internal static string CreditCashOutReceiptTitle {
            get {
                return ResourceManager.GetString("CreditCashOutReceiptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS Kiosk (Advanced).
        /// </summary>
        internal static string DeviceAdvancedPOSKiosk {
            get {
                return ResourceManager.GetString("DeviceAdvancedPOSKiosk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS Kiosk (B3).
        /// </summary>
        internal static string DeviceB3Kiosk {
            get {
                return ResourceManager.GetString("DeviceB3Kiosk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS Kiosk (Buy Again).
        /// </summary>
        internal static string DeviceBuyAgainKiosk {
            get {
                return ResourceManager.GetString("DeviceBuyAgainKiosk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caller.
        /// </summary>
        internal static string DeviceCaller {
            get {
                return ResourceManager.GetString("DeviceCaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crate Server.
        /// </summary>
        internal static string DeviceCrateServer {
            get {
                return ResourceManager.GetString("DeviceCrateServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer2.
        /// </summary>
        internal static string DeviceExplorer {
            get {
                return ResourceManager.GetString("DeviceExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed.
        /// </summary>
        internal static string DeviceFixedUnit {
            get {
                return ResourceManager.GetString("DeviceFixedUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS Kiosk (Hybrid).
        /// </summary>
        internal static string DeviceHybridKiosk {
            get {
                return ResourceManager.GetString("DeviceHybridKiosk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiosk.
        /// </summary>
        internal static string DeviceKiosk {
            get {
                return ResourceManager.GetString("DeviceKiosk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        internal static string DeviceManagement {
            get {
                return ResourceManager.GetString("DeviceManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS.
        /// </summary>
        internal static string DevicePOS {
            get {
                return ResourceManager.GetString("DevicePOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS / Management.
        /// </summary>
        internal static string DevicePOSManagement {
            get {
                return ResourceManager.GetString("DevicePOSManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS (Portable).
        /// </summary>
        internal static string DevicePOSPortable {
            get {
                return ResourceManager.GetString("DevicePOSPortable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Display.
        /// </summary>
        internal static string DeviceRemoteDisplay {
            get {
                return ResourceManager.GetString("DeviceRemoteDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS Kiosk (Simple).
        /// </summary>
        internal static string DeviceSimplePOSKiosk {
            get {
                return ResourceManager.GetString("DeviceSimplePOSKiosk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ted-E.
        /// </summary>
        internal static string DeviceTablet {
            get {
                return ResourceManager.GetString("DeviceTablet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracker.
        /// </summary>
        internal static string DeviceTracker {
            get {
                return ResourceManager.GetString("DeviceTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traveler.
        /// </summary>
        internal static string DeviceTraveler {
            get {
                return ResourceManager.GetString("DeviceTraveler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traveler II.
        /// </summary>
        internal static string DeviceTraveler2 {
            get {
                return ResourceManager.GetString("DeviceTraveler2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UK Socket Server.
        /// </summary>
        internal static string DeviceUKSocketServer {
            get {
                return ResourceManager.GetString("DeviceUKSocketServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Defined.
        /// </summary>
        internal static string DeviceUserDefined {
            get {
                return ResourceManager.GetString("DeviceUserDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VLT Bingo Kiosk.
        /// </summary>
        internal static string DeviceVLTBingoKiosk {
            get {
                return ResourceManager.GetString("DeviceVLTBingoKiosk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Disabled).
        /// </summary>
        internal static string DisabledText {
            get {
                return ResourceManager.GetString("DisabledText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Elite {
            get {
                object obj = ResourceManager.GetObject("Elite", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a numeric value..
        /// </summary>
        internal static string EnterNumber {
            get {
                return ResourceManager.GetString("EnterNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        internal static string FreeSpace {
            get {
                return ResourceManager.GetString("FreeSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve the machine&apos;s information from the server.  Reason: {0}.
        /// </summary>
        internal static string GetMachineFailed {
            get {
                return ResourceManager.GetString("GetMachineFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve the machine list from the server.  Reason: {0}.
        /// </summary>
        internal static string GetMachineListFailed {
            get {
                return ResourceManager.GetString("GetMachineListFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve the player from the server.  Reason: {0}.
        /// </summary>
        internal static string GetPlayerFailed {
            get {
                return ResourceManager.GetString("GetPlayerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve the player(s) from the server.  Reason: {0}.
        /// </summary>
        internal static string GetPlayerListFailed {
            get {
                return ResourceManager.GetString("GetPlayerListFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GreenButtonDown {
            get {
                object obj = ResourceManager.GetObject("GreenButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GreenButtonUp {
            get {
                object obj = ResourceManager.GetObject("GreenButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server is busy.
        /// </summary>
        internal static string GTIServerErrorBusy {
            get {
                return ResourceManager.GetString("GTIServerErrorBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card sales unavailable.
        /// </summary>
        internal static string GTIServerErrorCardSalesUnavailable {
            get {
                return ResourceManager.GetString("GTIServerErrorCardSalesUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error communicating with the Cental server.
        /// </summary>
        internal static string GTIServerErrorCentralComm {
            get {
                return ResourceManager.GetString("GTIServerErrorCentralComm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error committing tranaction.
        /// </summary>
        internal static string GTIServerErrorCommitTrans {
            get {
                return ResourceManager.GetString("GTIServerErrorCommitTrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error starting connection.
        /// </summary>
        internal static string GTIServerErrorConnect {
            get {
                return ResourceManager.GetString("GTIServerErrorConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error accessing database.
        /// </summary>
        internal static string GTIServerErrorDbAccess {
            get {
                return ResourceManager.GetString("GTIServerErrorDbAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate table entry.
        /// </summary>
        internal static string GTIServerErrorDupTable {
            get {
                return ResourceManager.GetString("GTIServerErrorDupTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General error.
        /// </summary>
        internal static string GTIServerErrorGeneral {
            get {
                return ResourceManager.GetString("GTIServerErrorGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is insufficient inventory.
        /// </summary>
        internal static string GTIServerErrorInsufficientInventory {
            get {
                return ResourceManager.GetString("GTIServerErrorInsufficientInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current item is in use.
        /// </summary>
        internal static string GTIServerErrorInUse {
            get {
                return ResourceManager.GetString("GTIServerErrorInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error allocating memory.
        /// </summary>
        internal static string GTIServerErrorMemAlloc {
            get {
                return ResourceManager.GetString("GTIServerErrorMemAlloc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing table entry.
        /// </summary>
        internal static string GTIServerErrorMissingTable {
            get {
                return ResourceManager.GetString("GTIServerErrorMissingTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No message handler found.
        /// </summary>
        internal static string GTIServerErrorMsgHandler {
            get {
                return ResourceManager.GetString("GTIServerErrorMsgHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error starting the multicast.
        /// </summary>
        internal static string GTIServerErrorMulticast {
            get {
                return ResourceManager.GetString("GTIServerErrorMulticast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No requests are pending.
        /// </summary>
        internal static string GTIServerErrorNoRequests {
            get {
                return ResourceManager.GetString("GTIServerErrorNoRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient rights.
        /// </summary>
        internal static string GTIServerErrorNoRights {
            get {
                return ResourceManager.GetString("GTIServerErrorNoRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stored procedure not found.
        /// </summary>
        internal static string GTIServerErrorNoSProc {
            get {
                return ResourceManager.GetString("GTIServerErrorNoSProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter error.
        /// </summary>
        internal static string GTIServerErrorParam {
            get {
                return ResourceManager.GetString("GTIServerErrorParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests are pending.
        /// </summary>
        internal static string GTIServerErrorRequestPend {
            get {
                return ResourceManager.GetString("GTIServerErrorRequestPend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error rolling back transaction.
        /// </summary>
        internal static string GTIServerErrorRollbackTrans {
            get {
                return ResourceManager.GetString("GTIServerErrorRollbackTrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL error.
        /// </summary>
        internal static string GTIServerErrorSQL {
            get {
                return ResourceManager.GetString("GTIServerErrorSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error starting transaction.
        /// </summary>
        internal static string GTIServerErrorStartTrans {
            get {
                return ResourceManager.GetString("GTIServerErrorStartTrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String was too long.
        /// </summary>
        internal static string GTIServerErrorString {
            get {
                return ResourceManager.GetString("GTIServerErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string GTIServerErrorSuccess {
            get {
                return ResourceManager.GetString("GTIServerErrorSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized action.
        /// </summary>
        internal static string GTIServerErrorUnauth {
            get {
                return ResourceManager.GetString("GTIServerErrorUnauth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        internal static string GTIServerErrorUnknown {
            get {
                return ResourceManager.GetString("GTIServerErrorUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating a table.
        /// </summary>
        internal static string GTIServerErrorUpdateTable {
            get {
                return ResourceManager.GetString("GTIServerErrorUpdateTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error writing to a file.
        /// </summary>
        internal static string GTIServerErrorWriteFile {
            get {
                return ResourceManager.GetString("GTIServerErrorWriteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **INCOMPLETE**
        ///**TRANSACTION**.
        /// </summary>
        internal static string IncompleteTransactionTitle {
            get {
                return ResourceManager.GetString("IncompleteTransactionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **INCOMPLETE**.
        /// </summary>
        internal static string IncompleteTransactionTitle1 {
            get {
                return ResourceManager.GetString("IncompleteTransactionTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **TRANSACTION**.
        /// </summary>
        internal static string IncompleteTransactionTitle2 {
            get {
                return ResourceManager.GetString("IncompleteTransactionTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid {0} response received from server..
        /// </summary>
        internal static string InvalidMessageResponse {
            get {
                return ResourceManager.GetString("InvalidMessageResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LoadingScreen1024 {
            get {
                object obj = ResourceManager.GetObject("LoadingScreen1024", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LoadingScreen800 {
            get {
                object obj = ResourceManager.GetObject("LoadingScreen800", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        internal static string Machine {
            get {
                return ResourceManager.GetString("Machine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MID {0}.
        /// </summary>
        internal static string MachineId {
            get {
                return ResourceManager.GetString("MachineId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Number.
        /// </summary>
        internal static string MachineNumber {
            get {
                return ResourceManager.GetString("MachineNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MagCardBack {
            get {
                object obj = ResourceManager.GetObject("MagCardBack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MagCardBackTouch {
            get {
                object obj = ResourceManager.GetObject("MagCardBackTouch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to initialize communication to EliteMCP..
        /// </summary>
        internal static string MCPNotActive {
            get {
                return ResourceManager.GetString("MCPNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MessageBack {
            get {
                object obj = ResourceManager.GetObject("MessageBack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MessageBackTouch {
            get {
                object obj = ResourceManager.GetObject("MessageBackTouch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Abort.
        /// </summary>
        internal static string MessageFormAbort {
            get {
                return ResourceManager.GetString("MessageFormAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string MessageFormCancel {
            get {
                return ResourceManager.GetString("MessageFormCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C&amp;ontinue.
        /// </summary>
        internal static string MessageFormContinue {
            get {
                return ResourceManager.GetString("MessageFormContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Force.
        /// </summary>
        internal static string MessageFormForce {
            get {
                return ResourceManager.GetString("MessageFormForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Ignore.
        /// </summary>
        internal static string MessageFormIgnore {
            get {
                return ResourceManager.GetString("MessageFormIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;No.
        /// </summary>
        internal static string MessageFormNo {
            get {
                return ResourceManager.GetString("MessageFormNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OK.
        /// </summary>
        internal static string MessageFormOk {
            get {
                return ResourceManager.GetString("MessageFormOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Retry.
        /// </summary>
        internal static string MessageFormRetry {
            get {
                return ResourceManager.GetString("MessageFormRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Yes.
        /// </summary>
        internal static string MessageFormYes {
            get {
                return ResourceManager.GetString("MessageFormYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message: {0}.
        /// </summary>
        internal static string MessageName {
            get {
                return ResourceManager.GetString("MessageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} message payload is the wrong size..
        /// </summary>
        internal static string MessagePayloadWrongSize {
            get {
                return ResourceManager.GetString("MessagePayloadWrongSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get device type data .
        /// </summary>
        internal static string NoDeviceTypes {
            get {
                return ResourceManager.GetString("NoDeviceTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No machine is selected..
        /// </summary>
        internal static string NoMachineSel {
            get {
                return ResourceManager.GetString("NoMachineSel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No player is selected..
        /// </summary>
        internal static string NoPlayerSel {
            get {
                return ResourceManager.GetString("NoPlayerSel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to obj is not a .
        /// </summary>
        internal static string NotAClass {
            get {
                return ResourceManager.GetString("NotAClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No text was entered..
        /// </summary>
        internal static string NoTextEntered {
            get {
                return ResourceManager.GetString("NoTextEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Won:.
        /// </summary>
        internal static string PayoutReceiptDateWon {
            get {
                return ResourceManager.GetString("PayoutReceiptDateWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game:.
        /// </summary>
        internal static string PayoutReceiptGame {
            get {
                return ResourceManager.GetString("PayoutReceiptGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        internal static string PayoutReceiptGameType {
            get {
                return ResourceManager.GetString("PayoutReceiptGameType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winners:.
        /// </summary>
        internal static string PayoutReceiptNumWinners {
            get {
                return ResourceManager.GetString("PayoutReceiptNumWinners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid Out:.
        /// </summary>
        internal static string PayoutReceiptPaidOut {
            get {
                return ResourceManager.GetString("PayoutReceiptPaidOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid By.
        /// </summary>
        internal static string PayoutReceiptPayStaff {
            get {
                return ResourceManager.GetString("PayoutReceiptPayStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payout Receipt.
        /// </summary>
        internal static string PayOutReceiptTitle {
            get {
                return ResourceManager.GetString("PayOutReceiptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Prize:.
        /// </summary>
        internal static string PayoutReceiptTotalPrize {
            get {
                return ResourceManager.GetString("PayoutReceiptTotalPrize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winner.
        /// </summary>
        internal static string PayoutReceiptWinner {
            get {
                return ResourceManager.GetString("PayoutReceiptWinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Player Id {0}].
        /// </summary>
        internal static string PlayerNoName {
            get {
                return ResourceManager.GetString("PlayerNoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Presale Receipt.
        /// </summary>
        internal static string PresaleReceiptTitle {
            get {
                return ResourceManager.GetString("PresaleReceiptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount:.
        /// </summary>
        internal static string ReceiptAmount {
            get {
                return ResourceManager.GetString("ReceiptAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}                                Page {1}/{2}.
        /// </summary>
        internal static string ReceiptBingoCardDisputeHeader {
            get {
                return ResourceManager.GetString("ReceiptBingoCardDisputeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt #: {0}          Gaming Date: {1}          Page {2}/{3}.
        /// </summary>
        internal static string ReceiptBingoCardHeader {
            get {
                return ResourceManager.GetString("ReceiptBingoCardHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Balance ({0}):.
        /// </summary>
        internal static string ReceiptCashOutBalance {
            get {
                return ResourceManager.GetString("ReceiptCashOutBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashed Out ({0}):.
        /// </summary>
        internal static string ReceiptCashOutCashedOut {
            get {
                return ResourceManager.GetString("ReceiptCashOutCashedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Rate:.
        /// </summary>
        internal static string ReceiptCashOutExchangeRate {
            get {
                return ResourceManager.GetString("ReceiptCashOutExchangeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Org. Balance ({0}):.
        /// </summary>
        internal static string ReceiptCashOutOriginal {
            get {
                return ResourceManager.GetString("ReceiptCashOutOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crystal Ball Cards.
        /// </summary>
        internal static string ReceiptCBBTitle {
            get {
                return ResourceManager.GetString("ReceiptCBBTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charity Information.
        /// </summary>
        internal static string ReceiptChaityTitle {
            get {
                return ResourceManager.GetString("ReceiptChaityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License #:.
        /// </summary>
        internal static string ReceiptCharityLicense {
            get {
                return ResourceManager.GetString("ReceiptCharityLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string ReceiptCharityName {
            get {
                return ResourceManager.GetString("ReceiptCharityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Id:.
        /// </summary>
        internal static string ReceiptCharityTaxId {
            get {
                return ResourceManager.GetString("ReceiptCharityTaxId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Id:.
        /// </summary>
        internal static string ReceiptClientId {
            get {
                return ResourceManager.GetString("ReceiptClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game {0}-{1}:.
        /// </summary>
        internal static string ReceiptContinuationGame {
            get {
                return ResourceManager.GetString("ReceiptContinuationGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupons:.
        /// </summary>
        internal static string ReceiptCoupons {
            get {
                return ResourceManager.GetString("ReceiptCoupons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ELECTRONIC VALIDATED.
        /// </summary>
        internal static string ReceiptElectronicValidated {
            get {
                return ResourceManager.GetString("ReceiptElectronicValidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game {0}:.
        /// </summary>
        internal static string ReceiptGame {
            get {
                return ResourceManager.GetString("ReceiptGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gaming Date:.
        /// </summary>
        internal static string ReceiptGamingDate {
            get {
                return ResourceManager.GetString("ReceiptGamingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issued By:.
        /// </summary>
        internal static string ReceiptIssuedBy {
            get {
                return ResourceManager.GetString("ReceiptIssuedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issued On:.
        /// </summary>
        internal static string ReceiptIssuedOn {
            get {
                return ResourceManager.GetString("ReceiptIssuedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issued To:.
        /// </summary>
        internal static string ReceiptIssuedTo {
            get {
                return ResourceManager.GetString("ReceiptIssuedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine:.
        /// </summary>
        internal static string ReceiptMachineName {
            get {
                return ResourceManager.GetString("ReceiptMachineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malfunction Voids.
        /// </summary>
        internal static string ReceiptMalfunction1 {
            get {
                return ResourceManager.GetString("ReceiptMalfunction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Pays and Plays.
        /// </summary>
        internal static string ReceiptMalfunction2 {
            get {
                return ResourceManager.GetString("ReceiptMalfunction2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt #:.
        /// </summary>
        internal static string ReceiptNumber {
            get {
                return ResourceManager.GetString("ReceiptNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack Number.
        /// </summary>
        internal static string ReceiptPackNumber {
            get {
                return ResourceManager.GetString("ReceiptPackNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper Packs Sold.
        /// </summary>
        internal static string ReceiptPaperPacksSold {
            get {
                return ResourceManager.GetString("ReceiptPaperPacksSold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAPER VALIDATED.
        /// </summary>
        internal static string ReceiptPaperValidated {
            get {
                return ResourceManager.GetString("ReceiptPaperValidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account #:.
        /// </summary>
        internal static string ReceiptPlayerIdentity {
            get {
                return ResourceManager.GetString("ReceiptPlayerIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Name:.
        /// </summary>
        internal static string ReceiptPlayerName {
            get {
                return ResourceManager.GetString("ReceiptPlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player #:.
        /// </summary>
        internal static string ReceiptPlayerNumber {
            get {
                return ResourceManager.GetString("ReceiptPlayerNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Pts.:.
        /// </summary>
        internal static string ReceiptPlayerPoints {
            get {
                return ResourceManager.GetString("ReceiptPlayerPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pts. Earned:.
        /// </summary>
        internal static string ReceiptPlayerPointsEarned {
            get {
                return ResourceManager.GetString("ReceiptPlayerPointsEarned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pts. Redeemed:.
        /// </summary>
        internal static string ReceiptPlayerPointsRedeem {
            get {
                return ResourceManager.GetString("ReceiptPlayerPointsRedeem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pts. Redeemed:.
        /// </summary>
        internal static string ReceiptPlayerPointsUsed {
            get {
                return ResourceManager.GetString("ReceiptPlayerPointsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Balance:.
        /// </summary>
        internal static string ReceiptPlayerPointTotal {
            get {
                return ResourceManager.GetString("ReceiptPlayerPointTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pt Qual. Amt:.
        /// </summary>
        internal static string ReceiptPointQualifyingAmt {
            get {
                return ResourceManager.GetString("ReceiptPointQualifyingAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pts From Qual.:.
        /// </summary>
        internal static string ReceiptPointsFromQualifyingAmt {
            get {
                return ResourceManager.GetString("ReceiptPointsFromQualifyingAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepaid:.
        /// </summary>
        internal static string ReceiptPrepaidAmount {
            get {
                return ResourceManager.GetString("ReceiptPrepaidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redeemed:.
        /// </summary>
        internal static string ReceiptRedeemed {
            get {
                return ResourceManager.GetString("ReceiptRedeemed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ** Reprint **.
        /// </summary>
        internal static string ReceiptReprint {
            get {
                return ResourceManager.GetString("ReceiptReprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cards.
        /// </summary>
        internal static string ReceiptSalesCards {
            get {
                return ResourceManager.GetString("ReceiptSalesCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change:.
        /// </summary>
        internal static string ReceiptSalesChange {
            get {
                return ResourceManager.GetString("ReceiptSalesChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Fee:.
        /// </summary>
        internal static string ReceiptSalesDeviceFee {
            get {
                return ResourceManager.GetString("ReceiptSalesDeviceFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Rate:.
        /// </summary>
        internal static string ReceiptSalesExchangeRate {
            get {
                return ResourceManager.GetString("ReceiptSalesExchangeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Info Per Game.
        /// </summary>
        internal static string ReceiptSalesGameCardsHeader {
            get {
                return ResourceManager.GetString("ReceiptSalesGameCardsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game{0}:{1} .
        /// </summary>
        internal static string ReceiptSalesGameTotalCards {
            get {
                return ResourceManager.GetString("ReceiptSalesGameTotalCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grand Total ({0}):.
        /// </summary>
        internal static string ReceiptSalesGrandTotal {
            get {
                return ResourceManager.GetString("ReceiptSalesGrandTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sess  Qty            Points        Total.
        /// </summary>
        internal static string ReceiptSalesItemHeader1 {
            get {
                return ResourceManager.GetString("ReceiptSalesItemHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item               Redeemed.
        /// </summary>
        internal static string ReceiptSalesItemHeader2 {
            get {
                return ResourceManager.GetString("ReceiptSalesItemHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sess  Qty Item                     Total.
        /// </summary>
        internal static string ReceiptSalesItemHeaderNoPts1 {
            get {
                return ResourceManager.GetString("ReceiptSalesItemHeaderNoPts1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elec. Cards:.
        /// </summary>
        internal static string ReceiptSalesSessionElecCards {
            get {
                return ResourceManager.GetString("ReceiptSalesSessionElecCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper Cards:.
        /// </summary>
        internal static string ReceiptSalesSessionPaperCards {
            get {
                return ResourceManager.GetString("ReceiptSalesSessionPaperCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Cards:.
        /// </summary>
        internal static string ReceiptSalesSessionTotalCards {
            get {
                return ResourceManager.GetString("ReceiptSalesSessionTotalCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sess  Qty    Points        Total.
        /// </summary>
        internal static string ReceiptSalesSmallItemHeader1 {
            get {
                return ResourceManager.GetString("ReceiptSalesSmallItemHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item       Redeemed.
        /// </summary>
        internal static string ReceiptSalesSmallItemHeader2 {
            get {
                return ResourceManager.GetString("ReceiptSalesSmallItemHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sess  Qty Item             Total.
        /// </summary>
        internal static string ReceiptSalesSmallItemHeaderNoPts1 {
            get {
                return ResourceManager.GetString("ReceiptSalesSmallItemHeaderNoPts1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxes:.
        /// </summary>
        internal static string ReceiptSalesTaxes {
            get {
                return ResourceManager.GetString("ReceiptSalesTaxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Tendered:.
        /// </summary>
        internal static string ReceiptSalesTendered {
            get {
                return ResourceManager.GetString("ReceiptSalesTendered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Total({0}):.
        /// </summary>
        internal static string ReceiptSalesTotal {
            get {
                return ResourceManager.GetString("ReceiptSalesTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial #:.
        /// </summary>
        internal static string ReceiptSerialNumber {
            get {
                return ResourceManager.GetString("ReceiptSerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session {0}.
        /// </summary>
        internal static string ReceiptSession {
            get {
                return ResourceManager.GetString("ReceiptSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pts Rdm:.
        /// </summary>
        internal static string ReceiptSmallPlayerPointsRedeem {
            get {
                return ResourceManager.GetString("ReceiptSmallPlayerPointsRedeem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dev Fee:.
        /// </summary>
        internal static string ReceiptSmallSalesDeviceFee {
            get {
                return ResourceManager.GetString("ReceiptSmallSalesDeviceFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XRT:.
        /// </summary>
        internal static string ReceiptSmallSalesExchangeRate {
            get {
                return ResourceManager.GetString("ReceiptSmallSalesExchangeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amt Tnd:.
        /// </summary>
        internal static string ReceiptSmallSalesTendered {
            get {
                return ResourceManager.GetString("ReceiptSmallSalesTendered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ttl {0}:.
        /// </summary>
        internal static string ReceiptSmallSalesTotal {
            get {
                return ResourceManager.GetString("ReceiptSmallSalesTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subttl:.
        /// </summary>
        internal static string ReceiptSmallSubtotal {
            get {
                return ResourceManager.GetString("ReceiptSmallSubtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station:.
        /// </summary>
        internal static string ReceiptSoldFrom {
            get {
                return ResourceManager.GetString("ReceiptSoldFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashier:.
        /// </summary>
        internal static string ReceiptStaff {
            get {
                return ResourceManager.GetString("ReceiptStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal:.
        /// </summary>
        internal static string ReceiptSubtotal {
            get {
                return ResourceManager.GetString("ReceiptSubtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Date:.
        /// </summary>
        internal static string ReceiptTransactionDate {
            get {
                return ResourceManager.GetString("ReceiptTransactionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit #:.
        /// </summary>
        internal static string ReceiptUnitNumber {
            get {
                return ResourceManager.GetString("ReceiptUnitNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RedButtonDown {
            get {
                object obj = ResourceManager.GetObject("RedButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RedButtonUp {
            get {
                object obj = ResourceManager.GetObject("RedButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund On:.
        /// </summary>
        internal static string RefundReceiptDate {
            get {
                return ResourceManager.GetString("RefundReceiptDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund #:.
        /// </summary>
        internal static string RefundReceiptNumber {
            get {
                return ResourceManager.GetString("RefundReceiptNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund By:.
        /// </summary>
        internal static string RefundReceiptStaff {
            get {
                return ResourceManager.GetString("RefundReceiptStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Refund Receipt.
        /// </summary>
        internal static string RefundReceiptTitle {
            get {
                return ResourceManager.GetString("RefundReceiptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Return Receipt.
        /// </summary>
        internal static string ReturnReceiptTitle {
            get {
                return ResourceManager.GetString("ReturnReceiptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Sale Receipt.
        /// </summary>
        internal static string SaleReceiptTitle {
            get {
                return ResourceManager.GetString("SaleReceiptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By Number:.
        /// </summary>
        internal static string SearchByNumber {
            get {
                return ResourceManager.GetString("SearchByNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Machines.
        /// </summary>
        internal static string SearchMachines {
            get {
                return ResourceManager.GetString("SearchMachines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select &amp;Machine.
        /// </summary>
        internal static string SelectMachine {
            get {
                return ResourceManager.GetString("SelectMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server communication lost..
        /// </summary>
        internal static string ServerCommFailed {
            get {
                return ResourceManager.GetString("ServerCommFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server returned error: {0} ({1})..
        /// </summary>
        internal static string ServerErrorCode {
            get {
                return ResourceManager.GetString("ServerErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session:.
        /// </summary>
        internal static string SessionTitle {
            get {
                return ResourceManager.GetString("SessionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   S L I N G O .
        /// </summary>
        internal static string SlingoCardHeader {
            get {
                return ResourceManager.GetString("SlingoCardHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SplashscreenBG {
            get {
                object obj = ResourceManager.GetObject("SplashscreenBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SQLConnection {
            get {
                return ResourceManager.GetString("SQLConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Star {
            get {
                object obj = ResourceManager.GetObject("Star", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash.
        /// </summary>
        internal static string TenderTypeCash {
            get {
                return ResourceManager.GetString("TenderTypeCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orig. Receipt #:.
        /// </summary>
        internal static string UnitTransferReceiptOrigNum {
            get {
                return ResourceManager.GetString("UnitTransferReceiptOrigNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Transfer Receipt.
        /// </summary>
        internal static string UnitTransferReceiptTitle {
            get {
                return ResourceManager.GetString("UnitTransferReceiptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferred To.
        /// </summary>
        internal static string UnitTransferReceiptTransfer {
            get {
                return ResourceManager.GetString("UnitTransferReceiptTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown bingo game/card combination..
        /// </summary>
        internal static string UnknownBingoCard {
            get {
                return ResourceManager.GetString("UnknownBingoCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown card level id received from server..
        /// </summary>
        internal static string UnknownCardLevel {
            get {
                return ResourceManager.GetString("UnknownCardLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voided On:.
        /// </summary>
        internal static string VoidReceiptDate {
            get {
                return ResourceManager.GetString("VoidReceiptDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device:.
        /// </summary>
        internal static string VoidReceiptDevice {
            get {
                return ResourceManager.GetString("VoidReceiptDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Void #:.
        /// </summary>
        internal static string VoidReceiptNumber {
            get {
                return ResourceManager.GetString("VoidReceiptNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pts. Removed:.
        /// </summary>
        internal static string VoidReceiptPtsRemoved {
            get {
                return ResourceManager.GetString("VoidReceiptPtsRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pts. Returned:.
        /// </summary>
        internal static string VoidReceiptPtsReturned {
            get {
                return ResourceManager.GetString("VoidReceiptPtsReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total:.
        /// </summary>
        internal static string VoidReceiptPtsTotal {
            get {
                return ResourceManager.GetString("VoidReceiptPtsTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voided By:.
        /// </summary>
        internal static string VoidReceiptStaff {
            get {
                return ResourceManager.GetString("VoidReceiptStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Void Receipt.
        /// </summary>
        internal static string VoidReceiptTitle {
            get {
                return ResourceManager.GetString("VoidReceiptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt Total:.
        /// </summary>
        internal static string VoidReceiptTotal {
            get {
                return ResourceManager.GetString("VoidReceiptTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WaitAnimation {
            get {
                object obj = ResourceManager.GetObject("WaitAnimation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WaitBack {
            get {
                object obj = ResourceManager.GetObject("WaitBack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for machines, please wait..
        /// </summary>
        internal static string WaitFormFindingMachines {
            get {
                return ResourceManager.GetString("WaitFormFindingMachines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for players, please wait..
        /// </summary>
        internal static string WaitFormFindingPlayers {
            get {
                return ResourceManager.GetString("WaitFormFindingPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting machine data, please wait..
        /// </summary>
        internal static string WaitFormGettingMachine {
            get {
                return ResourceManager.GetString("WaitFormGettingMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting player data, please wait..
        /// </summary>
        internal static string WaitFormGettingPlayer {
            get {
                return ResourceManager.GetString("WaitFormGettingPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap YellowButtonDown {
            get {
                object obj = ResourceManager.GetObject("YellowButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap YellowButtonUp {
            get {
                object obj = ResourceManager.GetObject("YellowButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
